// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/mangahub.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manga struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manga) Reset() {
	*x = Manga{}
	mi := &file_api_proto_mangahub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manga) ProtoMessage() {}

func (x *Manga) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mangahub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manga.ProtoReflect.Descriptor instead.
func (*Manga) Descriptor() ([]byte, []int) {
	return file_api_proto_mangahub_proto_rawDescGZIP(), []int{0}
}

func (x *Manga) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Manga) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Manga) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manga) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UserProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MangaId       int32                  `protobuf:"varint,1,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	LastChapter   int32                  `protobuf:"varint,2,opt,name=last_chapter,json=lastChapter,proto3" json:"last_chapter,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProgress) Reset() {
	*x = UserProgress{}
	mi := &file_api_proto_mangahub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProgress) ProtoMessage() {}

func (x *UserProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mangahub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProgress.ProtoReflect.Descriptor instead.
func (*UserProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_mangahub_proto_rawDescGZIP(), []int{1}
}

func (x *UserProgress) GetMangaId() int32 {
	if x != nil {
		return x.MangaId
	}
	return 0
}

func (x *UserProgress) GetLastChapter() int32 {
	if x != nil {
		return x.LastChapter
	}
	return 0
}

func (x *UserProgress) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type EventNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventNotification) Reset() {
	*x = EventNotification{}
	mi := &file_api_proto_mangahub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventNotification) ProtoMessage() {}

func (x *EventNotification) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mangahub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventNotification.ProtoReflect.Descriptor instead.
func (*EventNotification) Descriptor() ([]byte, []int) {
	return file_api_proto_mangahub_proto_rawDescGZIP(), []int{2}
}

func (x *EventNotification) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *EventNotification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EventNotification) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMangaRequest) Reset() {
	*x = GetMangaRequest{}
	mi := &file_api_proto_mangahub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaRequest) ProtoMessage() {}

func (x *GetMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mangahub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaRequest.ProtoReflect.Descriptor instead.
func (*GetMangaRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mangahub_proto_rawDescGZIP(), []int{3}
}

func (x *GetMangaRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MangaId       int32                  `protobuf:"varint,1,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	Chapter       int32                  `protobuf:"varint,2,opt,name=chapter,proto3" json:"chapter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgressRequest) Reset() {
	*x = UpdateProgressRequest{}
	mi := &file_api_proto_mangahub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressRequest) ProtoMessage() {}

func (x *UpdateProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mangahub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressRequest.ProtoReflect.Descriptor instead.
func (*UpdateProgressRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mangahub_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProgressRequest) GetMangaId() int32 {
	if x != nil {
		return x.MangaId
	}
	return 0
}

func (x *UpdateProgressRequest) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

type UpdateProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgressResponse) Reset() {
	*x = UpdateProgressResponse{}
	mi := &file_api_proto_mangahub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressResponse) ProtoMessage() {}

func (x *UpdateProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mangahub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressResponse.ProtoReflect.Descriptor instead.
func (*UpdateProgressResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mangahub_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProgressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMangaRequest) Reset() {
	*x = CreateMangaRequest{}
	mi := &file_api_proto_mangahub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMangaRequest) ProtoMessage() {}

func (x *CreateMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mangahub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMangaRequest.ProtoReflect.Descriptor instead.
func (*CreateMangaRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mangahub_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMangaRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMangaRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateMangaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMangaRequest) Reset() {
	*x = DeleteMangaRequest{}
	mi := &file_api_proto_mangahub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMangaRequest) ProtoMessage() {}

func (x *DeleteMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mangahub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMangaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMangaRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mangahub_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMangaRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMangaResponse) Reset() {
	*x = DeleteMangaResponse{}
	mi := &file_api_proto_mangahub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMangaResponse) ProtoMessage() {}

func (x *DeleteMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mangahub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMangaResponse.ProtoReflect.Descriptor instead.
func (*DeleteMangaResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mangahub_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMangaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_mangahub_proto protoreflect.FileDescriptor

const file_api_proto_mangahub_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/mangahub.proto\x12\vmangahub.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n" +
	"\x05Manga\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x87\x01\n" +
	"\fUserProgress\x12\x19\n" +
	"\bmanga_id\x18\x01 \x01(\x05R\amangaId\x12!\n" +
	"\flast_chapter\x18\x02 \x01(\x05R\vlastChapter\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"}\n" +
	"\x11EventNotification\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"!\n" +
	"\x0fGetMangaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"L\n" +
	"\x15UpdateProgressRequest\x12\x19\n" +
	"\bmanga_id\x18\x01 \x01(\x05R\amangaId\x12\x18\n" +
	"\achapter\x18\x02 \x01(\x05R\achapter\"L\n" +
	"\x16UpdateProgressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"d\n" +
	"\x12CreateMangaRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"$\n" +
	"\x12DeleteMangaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"/\n" +
	"\x13DeleteMangaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf4\x01\n" +
	"\fMangaService\x12<\n" +
	"\bGetManga\x12\x1c.mangahub.v1.GetMangaRequest\x1a\x12.mangahub.v1.Manga\x12Y\n" +
	"\x0eUpdateProgress\x12\".mangahub.v1.UpdateProgressRequest\x1a#.mangahub.v1.UpdateProgressResponse\x12K\n" +
	"\x0fSubscribeEvents\x12\x16.google.protobuf.Empty\x1a\x1e.mangahub.v1.EventNotification0\x012\xa4\x01\n" +
	"\fAdminService\x12B\n" +
	"\vCreateManga\x12\x1f.mangahub.v1.CreateMangaRequest\x1a\x12.mangahub.v1.Manga\x12P\n" +
	"\vDeleteManga\x12\x1f.mangahub.v1.DeleteMangaRequest\x1a .mangahub.v1.DeleteMangaResponseB!Z\x1fgithub.com/user/mangahub/pkg/pbb\x06proto3"

var (
	file_api_proto_mangahub_proto_rawDescOnce sync.Once
	file_api_proto_mangahub_proto_rawDescData []byte
)

func file_api_proto_mangahub_proto_rawDescGZIP() []byte {
	file_api_proto_mangahub_proto_rawDescOnce.Do(func() {
		file_api_proto_mangahub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_mangahub_proto_rawDesc), len(file_api_proto_mangahub_proto_rawDesc)))
	})
	return file_api_proto_mangahub_proto_rawDescData
}

var file_api_proto_mangahub_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_mangahub_proto_goTypes = []any{
	(*Manga)(nil),                  // 0: mangahub.v1.Manga
	(*UserProgress)(nil),           // 1: mangahub.v1.UserProgress
	(*EventNotification)(nil),      // 2: mangahub.v1.EventNotification
	(*GetMangaRequest)(nil),        // 3: mangahub.v1.GetMangaRequest
	(*UpdateProgressRequest)(nil),  // 4: mangahub.v1.UpdateProgressRequest
	(*UpdateProgressResponse)(nil), // 5: mangahub.v1.UpdateProgressResponse
	(*CreateMangaRequest)(nil),     // 6: mangahub.v1.CreateMangaRequest
	(*DeleteMangaRequest)(nil),     // 7: mangahub.v1.DeleteMangaRequest
	(*DeleteMangaResponse)(nil),    // 8: mangahub.v1.DeleteMangaResponse
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 10: google.protobuf.Empty
}
var file_api_proto_mangahub_proto_depIdxs = []int32{
	9,  // 0: mangahub.v1.UserProgress.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 1: mangahub.v1.EventNotification.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 2: mangahub.v1.MangaService.GetManga:input_type -> mangahub.v1.GetMangaRequest
	4,  // 3: mangahub.v1.MangaService.UpdateProgress:input_type -> mangahub.v1.UpdateProgressRequest
	10, // 4: mangahub.v1.MangaService.SubscribeEvents:input_type -> google.protobuf.Empty
	6,  // 5: mangahub.v1.AdminService.CreateManga:input_type -> mangahub.v1.CreateMangaRequest
	7,  // 6: mangahub.v1.AdminService.DeleteManga:input_type -> mangahub.v1.DeleteMangaRequest
	0,  // 7: mangahub.v1.MangaService.GetManga:output_type -> mangahub.v1.Manga
	5,  // 8: mangahub.v1.MangaService.UpdateProgress:output_type -> mangahub.v1.UpdateProgressResponse
	2,  // 9: mangahub.v1.MangaService.SubscribeEvents:output_type -> mangahub.v1.EventNotification
	0,  // 10: mangahub.v1.AdminService.CreateManga:output_type -> mangahub.v1.Manga
	8,  // 11: mangahub.v1.AdminService.DeleteManga:output_type -> mangahub.v1.DeleteMangaResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_mangahub_proto_init() }
func file_api_proto_mangahub_proto_init() {
	if File_api_proto_mangahub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_mangahub_proto_rawDesc), len(file_api_proto_mangahub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_mangahub_proto_goTypes,
		DependencyIndexes: file_api_proto_mangahub_proto_depIdxs,
		MessageInfos:      file_api_proto_mangahub_proto_msgTypes,
	}.Build()
	File_api_proto_mangahub_proto = out.File
	file_api_proto_mangahub_proto_goTypes = nil
	file_api_proto_mangahub_proto_depIdxs = nil
}
